### PR TITLE
rename the file name order for easier access

### PR DESCRIPTION
**Pull request by rogersaloo**
Thanks for the hardworking in explaining the papers. Made a small change if acceptable to you.
I realized since we are beginning a new year most of the file dates and months will mix up(2023,2024) hence difficult to find.
I thought YYYYMMDD may help organize them better. 
Keep going! Thanks.

### CODE REVIEW

**Comment by julien-blanchon** [comment]
Yes make more sense 👍

**Comment by YanivDorGalron** [comment]
i agree.
in addition, it might be easier to find if the name of the stream will be added to the name of the files

**Comment by hu-po** [comment]
Damn sorry, this got buried in my inbox and I didn't see it until now. I can see your point, but it would then require me changing the links on all the video descriptions to match the name change. So I think ill just keep it as is until I make a new repo with a better naming scheme.

**Comment by hu-po** [comment]
made a new repo with your suggestions: https://github.com/hu-po/docs

thanks everyone :heart:

**Pull request closed without merging**
